# .air.toml

# Root of the project (where go.mod is located)
root = "."

# Temporary build output directory
tmp_dir = "tmp"

[build]
  # Build command: compile the app from ./cmd/pipeline
  cmd = "go build -o ./tmp/pipeline ./cmd/pipeline"
  
  # Binary that air should run after building
  bin = "tmp/pipeline"
  
  # File types to watch
  include_ext = ["go", "tpl", "tmpl", "html", "json", "yaml"]
  
  # Directories to ignore (to prevent rebuild loops)
  exclude_dir = ["assets", "tmp", "vendor"]

  # Optional: wait for 1 second before rebuilding (useful if saving many files at once)
  delay = 1000

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[misc]
  # Clean tmp dir on exit
  clean_on_exit = true
